### PR TITLE
Fixed windows compatibility

### PR DESCRIPTION
**Pull request by dawnerd**
Changed fs.watchFile to use newer fs.watch api.

### CODE REVIEW

**Comment by tig** [comment]
Hi dawnerd: Are you sure this the only change needed?  I get a "watch Unknown system errono 123" when I apply this 2 line fix.

**Comment by dawnerd** [comment]
That fix worked for me. Not sure why you're getting that error.

**Comment by tig** [comment]
@dawnerd Is the project where you are using -assetmanager public? If so, would you mind pointing me at it so I can have another example of how to use it correctly. I'm having trouble knowing if I'm even doing it right. thanks.

**Comment by tig** [comment]
@dawnerd - I figured it out.  Your fix does, in fact, work fine. +1 on the pull request.

**Comment by prabirshrestha** [comment]
+1
would to have that pull in with a new npm package too.

**Pull request merged**
